### ISSUE TITLE
This is an old and nasty problem. I've tried to improve things a bit with https://github.com/ethz-asl/catkin_boost_python_buildtool/pull/2. Please have a look.

### ISSUE THREAD

**Issue by huangjiancong1** [ethz-asl/numpy_eigen#4]
This is an old and nasty problem. I've tried to improve things a bit with https://github.com/ethz-asl/catkin_boost_python_buildtool/pull/2. Please have a look.

Btw. do you actually need to build numpy_eigen? Could it be that you were trying to build your whole workspace and run into this problem? (see e.g. https://github.com/ethz-asl/minkindr/issues/67). In that case I recommend `catkin build SOMETHING` or placing `CATKIN_IGNORE` into some repos, e.g. `minkindr_python`.

_Originally posted by @HannesSommer in https://github.com/ethz-asl/numpy_eigen/issues/3#issuecomment-559996811_

I still don't understand how to find the `numpy/numpyconfig.h`? I need to compiler the package conclude it.

**Comment by HannesSommer** [comment]
@huangjiancong1 , does that mean you've tried the pull request you've mentioned and it worked for you? (I need some feedback to finally merge it in).
